import "./globals.css";
import { Inter } from "next/font/google";
import { LanguageContextProvider } from "../component/flagComponents/LanguageContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <LanguageContextProvider>{children}</LanguageContextProvider>
      </body>
    </html>
  );
}
